const masculino = [
    {
        "id": 27,
        "elenco": "masculino",
        "nome": "Gatito Fernández",
        "posicao": "Goleiro",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/gatito.png",
        "descricao": "Filho do goleiro Gato Fernández, que fez história e jogou na seleção paraguaia, Gatito seguiu a profissão do pai. Com passagens por clubes importantes da América do Sul, veio para o Brasil em 2014, teve boas atuações por Vitória e Figueirense, até chegar ao Botafogo.",
        "nome_completo": "Roberto Júnior Fernández Torres",
        "nascimento": "29/03/1988, em Assunção (PAR)",
        "altura": "1,91m"
    },
    {
        "id": 28,
        "elenco": "masculino",
        "nome": "Igo Gabriel",
        "posicao": "Goleiro",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/igo-gabriel.png",
        "descricao": "Cria das categorias de base do Botafogo, Igo Gabriel foi peça importante durante a temporada do do Sub-20 alvinegro, que foi campeão da Copa Rio OPG e vice-campeão da Copa do Brasil em 2021. Um dos destaques do time, o goleiro se firmou com excelentes atuações na base e agora espera repetir o sucesso incorporando o elenco profissional do Glorioso.",
        "nome_completo": "Igo Gabriel Santos Prereira",
        "nascimento": "13/10/2001, em Maceió-AL",
        "altura": "1,90m"
    },
    {
        "id": 29,
        "elenco": "masculino",
        "nome": "Lucas Perri",
        "posicao": "Goleiro",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/lucasperri.png",
        "descricao": "Goleiro promissor, Lucas Perri iniciou sua trajetória no futebol com a camisa do São Paulo e obteve inúmeras convocações para as seleções brasileiras de base. Após um ano de bastante destaque pelo Náutico, o arqueiro chega ao Glorioso para agregar valor para a defesa da meta alvinegra.",
        "nome_completo": "Lucas Estella Perri",
        "nascimento": "10/12/1997, em Valinhos (SP)",
        "altura": "1,97cm"
    },
    {
        "id": 30,
        "elenco": "masculino",
        "nome": "Hugo",
        "posicao": "Lateral",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/hugo.png",
        "descricao": "Jovem promissor, Hugo despontou no sub-20 do Botafogo e foi integrado gradativamente aos profissionais. O lateral-esquerdo trabalha com afinco para agarrar as oportunidades.",
        "nome_completo": "Hugo Gonçalves Ferreira Neto",
        "nascimento": "20/09/2001, em João Pessoa (PB)",
        "altura": "1,75m"
    },
    {
        "id": 31,
        "elenco": "masculino",
        "nome": "Rafael",
        "posicao": "Lateral",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/rafael-pereira.png",
        "descricao": "Escolhido pelo Botafogo desde sempre, chegou o momento de Rafael realizar o sonho de atuar em seu clube de coração. Com uma vasta experiência adquirida, após anos atuando entre os grandes do futebol europeu, o lateral se caracteriza por sua polivalência, um forte espírito de competitividade e boa técnica em campo.",
        "nome_completo": "Rafael Pereira da Silva",
        "nascimento": "09/07/1990, em Petrópolis (RJ)",
        "altura": "1,72m"
    },
    {
        "id": 32,
        "elenco": "masculino",
        "nome": "Marçal",
        "posicao": "Lateral",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/marcal.png",
        "descricao": "Jogador de grande experiência no futebol internacional, Fernando Marçal volta ao Brasil após 12 anos para defender o Botafogo. O lateral-esquerdo, que se destaca pela força física e polivalência, chega após uma temporada na Premier League, onde defendeu o Wolverhampton.",
        "nome_completo": "Fernando Marçal Oliveira",
        "nascimento": "19/02/1989, em São Paulo (SP)",
        "altura": "1,78m"
    },
    {
        "id": 33,
        "elenco": "masculino",
        "nome": "Di Plácido",
        "posicao": "Lateral",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/diplacido.png",
        "descricao": "Aguerrido e voluntarioso, Di Plácido chega ao Botafogo após anos de destaque no futebol argentino. O atleta passa a ser uma opção a mais para a lateral-direita e promete entregar o máximo de sí para defender as cores alvinegras em campo.",
        "nome_completo": "Leonel Di Plácido",
        "nascimento": "28/01/1994, em Buenos Aires-ARG",
        "altura": "1m74"
    },
    {
        "id": 34,
        "elenco": "masculino",
        "nome": "MATEO PONTE",
        "posicao": "Lateral",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/mateoponte.png",
        "descricao": "Titular e destaque na conquista da Copa do Mundo FIFA Sub-20 pelo Uruguai, Ponte é um jovem lateral direito que possui boa projeção ofensiva e muita segurança na marcação. Com muito potencial, Mateo chega para reforçar o setor defensivo do Glorioso e elevar o nível do elenco.",
        "nome_completo": "Mateo Ponte Costa",
        "nascimento": "24/05/2003, em Montevideo (URU)",
        "altura": "1,83 cm"
    },
    {
        "id": 35,
        "elenco": "masculino",
        "nome": "Philipe Sampaio",
        "posicao": "Zagueiro",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/philipe-sampaio.png",
        "descricao": "Formado no Santos, o defensor fez carreira e atuou por oito temporadas no futebol europeu. Conhecido como \"General\" na França, Sampaio fez parte da linha defensiva que ficou 700 minutos seguidos sem levar gols. Motivado com o desafio de construir uma nova história junto ao Glorioso, Sampaio chega como a primira contratação da Era John Textor.",
        "nome_completo": "Philipe Sampaio Azevedo",
        "nascimento": "11/11/1994, em São Paulo (SP)",
        "altura": "1,91m"
    },
    {
        "id": 36,
        "elenco": "masculino",
        "nome": "Victor Cuesta",
        "posicao": "Zagueiro",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/cuesta.png",
        "descricao": "Experiente defensor, Victor Cuesta chega para agregar valor ao setor defensivo do Botafogo. Eleito um dos melhores zagueiros do Campeonato Brasileiro nas temporadas 2018 e 2020, o Argentino tem um espírito de liderança característicos e chega com vontade de construir uma história de glórias com a camisa alvinegra.",
        "nome_completo": "Víctor Leandro Cuesta",
        "nascimento": "19/11/1988, em La Plata, Argentina",
        "altura": "1,87m"
    },
    {
        "id": 37,
        "elenco": "masculino",
        "nome": "Adryelson",
        "posicao": "Zagueiro",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/adryelson.png",
        "descricao": "Após uma breve passagem pelo futebol árabe, Adryelson chega ao Alvinegro para reforçar o setor defensivo. O zagueiro se destaca pela força, velocidade e impulsão.",
        "nome_completo": "Adryelson Shawann Lima Silva",
        "nascimento": "23/03/1998",
        "altura": "1,82m"
    },
    {
        "id": 38,
        "elenco": "masculino",
        "nome": "Sousa",
        "posicao": "Zagueiro",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/sousa.png",
        "descricao": "Zagueiro promissor e com personalidade, Sousa chegou aos profissionais do Botafogo com apenas 19 anos. Mira crescer na carreira, aprender e ganhar espaço dentro de campo.",
        "nome_completo": "David Sousa Albino",
        "nascimento": "04/07/2001, no Rio de Janeiro",
        "altura": "1,90m e 79kg"
    },
    {
        "id": 39,
        "elenco": "masculino",
        "nome": "Bastos",
        "posicao": "Zagueiro",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/bastos.png",
        "descricao": "Com uma carreira de destaque no futebol europeu, atuando por 4 temporadas na Lazio, da Itália, Quissanga Bastos é um zagueiro veloz que possui uma força física impressionante e um grande poder de impulsão. Anunciado com o hit especial: \"O Palanca-Negra é Alvinegro\", Bastos chega para somar forças ao setor defensivo do Botafogo.",
        "nome_completo": "Bartolomeu Jacinto Quissanga",
        "nascimento": "23/11/1991, em Luanda, na Angola",
        "altura": "1,84m"
    },
    {
        "id": 40,
        "elenco": "masculino",
        "nome": "Tchê Tchê",
        "posicao": "Volante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/tchetche.png",
        "descricao": "Volante de elevada qualidade técnica, Tchê Tchê coleciona conquistas na carreira. Tricampeão Brasileiro, da Copa do Brasil, entre outros títulos, o meia assume a histórica camisa 6 de Nilton Santos e chega ao Glorioso com o objetivo de ajudar na construção do novo projeto alvinegro.",
        "nome_completo": "Danilo das Neves Pinheiro",
        "nascimento": "30/08/1992, em São Paulo",
        "altura": "1,75m"
    },
    {
        "id": 41,
        "elenco": "masculino",
        "nome": "Danilo Barbosa",
        "posicao": "Volante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/danilobarbosa.png",
        "descricao": "Volante moderno, Danilo tem um currículo que reune muita experiência no futebol europeu. Revelado pelo Vasco, saiu muito cedo do país e atuou em Portugal, Espanha, Bélgica e França, antes de voltar ao Brasil para ser campeão da Libertadores pelo Palmeiras. Motivado, o volante quer voltar a jogar futebol com alegria pelo Botafogo.",
        "nome_completo": "Danilo Barbosa da Silva",
        "nascimento": "28/02/1996, em Simões Filho, (BA)",
        "altura": "1,83cm"
    },
    {
        "id": 42,
        "elenco": "masculino",
        "nome": "Patrick de Paula",
        "posicao": "Volante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/patrick-paula.png",
        "descricao": "Bicampeão da Libertadores e oriundo da Taça das Favelas do Rio de Janeiro, Patrick de Paula chegou ao Botafogo como a contratação mais cara da história alvinegra. Meio-campista reconhecido pelo talento e vigor físico, PK tem o toque de versatilidade que todo time precisa em campo.",
        "nome_completo": "Patrick de Paula Carreiro",
        "nascimento": "08/09/1999, em Rio de Janeiro, RJ",
        "altura": "1,78m"
    },
    {
        "id": 43,
        "elenco": "masculino",
        "nome": "Marlon Freitas",
        "posicao": "Volante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/marlon.png",
        "descricao": "Marlon Freitas chega ao Glorioso após se destacar na Sul-Americana e no Campeonato Brasileiro atuando pelo Atlético-GO. Marlon vem para somar ao elenco Alvinegro com sua força, visão de jogo e técnica. Revelado pelo Fluminense, o meio-campista também reúne experiências ao atuar fora do Brasil.",
        "nome_completo": "Marlon Rodrigues de Freitas",
        "nascimento": "27/03/1995, em Magé (RJ)",
        "altura": "1,85cm"
    },
    {
        "id": 44,
        "elenco": "masculino",
        "nome": "JP",
        "posicao": "Volante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/jp.png",
        "descricao": "Volante que alia versatilidade, combatividade e boa técnica, JP foi um atleta observado pelo departamento de scouting do Botafogo para integrar a equipe Sub-23. Após boas apresentações, o jovem conquistou seu espaço e foi opotunizado ao time principal em 2023.",
        "nome_completo": "João Pedro Galvão de Carvalho",
        "nascimento": "07/05/2001, em Cabo Frio (RJ)",
        "altura": "1m84"
    },
    {
        "id": 45,
        "elenco": "masculino",
        "nome": "Lucas Fernandes",
        "posicao": "Meia",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/lucas-fernandes.png",
        "descricao": "Meia de muita qualidade técnica, Lucas foi revelado pelo São Paulo e, desde muito jovem, se destacou com convocações para as Seleções Brasileiras de base. Após um período produtivo e de evolução no futebol português, Fernandes chega ao Botafogo para somar forças ao setor criativo da equipe.",
        "nome_completo": "Lucas Fernandes da Silva",
        "nascimento": "20/09/1997, em São Bernardo do Campo, SP",
        "altura": "1,75m"
    },
    {
        "id": 46,
        "elenco": "masculino",
        "nome": "Eduardo",
        "posicao": "Meia",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/eduardo.png",
        "descricao": "Meio-campista objetivo e com alto poder de definição, Eduardo construiu uma carreira sólida fora do país. Com experiências no futebol português e francês, o meia conquistou inúmeros títulos e se tornou ídolo na Arábia Saudita. Motivado com o desafio de defender o Glorioso, Eduardo espera conquistar também a torcida alvinegra.",
        "nome_completo": "Carlos Eduardo de Oliveira Alves",
        "nascimento": "17/10/1989, em Ribeirão Preto (SP)",
        "altura": "1,84cm"
    },
    {
        "id": 47,
        "elenco": "masculino",
        "nome": "Gabriel Pires",
        "posicao": "Meia",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/gabrielpires.png",
        "descricao": "Escolhido pelo Botafogo, Gabriel Pires é um meio-campo de muita qualidade técnica e com um bom toque de bola. Após fazer a base no Resende, o meia fez carreira na Europa e chega para realizar o sonho de atuar pelo clube de coração.",
        "nome_completo": "Gabriel Appelt Pires",
        "nascimento": "18/09/1993, Resende (RJ)",
        "altura": "1,87cm"
    },
    {
        "id": 48,
        "elenco": "masculino",
        "nome": "Jacob Montes",
        "posicao": "Meia",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/jacobmontes.png",
        "descricao": "Com passagens por Crystal Palace e RWD Molenbeek, Jacob Montes é um dos representantes do conceito multiclubes ideializado pelo acionista majoritário John Textor. O atleta norte-americano chega ao Botafogo para um intercâmbio e busca se adaptar a cultura brasileira.",
        "nome_completo": "Jacob Christian Montes",
        "nascimento": "20/10/1998, em Flórida-EUA",
        "altura": "1,80cm"
    },
    {
        "id": 49,
        "elenco": "masculino",
        "nome": "Raí",
        "posicao": "Meia",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/rai.png",
        "descricao": "Meia de muita habilidade e com notável qualidade nos passes, Raí chegou ao Botafogo com 11 anos de idade e tem orgulho de dizer que foi formado pela #BaseForte alvinegra. Após de destacar com o Sub-20 alvinegro, o jovem espera fazer bonito também na equipe profissional.",
        "nome_completo": "Rai da Silva Pessanha",
        "nascimento": "21/04/2002, em Duque de Caxias (RJ)",
        "altura": "1,71m"
    },
    {
        "id": 50,
        "elenco": "masculino",
        "nome": "Luis Henrique",
        "posicao": "Atacante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/luishenrique.png",
        "descricao": "Cria da base alvinegra, Luis Henrique está nem sua segunda passagem pelo Glorioso. O atacante retorna após vivência futebol europeu, ainda mais desenvolvido fisicamente. Se destaca em campo por bastante força, velocidade e objetividade nas ações ofensivas.",
        "nome_completo": "Luis Henrique Tomaz de Lima",
        "nascimento": "14/12/2001, em João Pessoa (PB)",
        "altura": "1,81cm"
    },
    {
        "id": 51,
        "elenco": "masculino",
        "nome": "Victor Sá",
        "posicao": "Atacante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/victor-sa.png",
        "descricao": "Atacante com passagem longa pelo futebol internacional, Victor Sá retorna ao Brasil para defender o Botafogo. Habilidoso e rápido, o jogador se apresenta como uma das ferramentas ofensivas do Clube na temporada.",
        "nome_completo": "João Victor Sá",
        "nascimento": "27/03/1994, em São José dos Campos, SP",
        "altura": "1,78m"
    },
    {
        "id": 52,
        "elenco": "masculino",
        "nome": "Diego Costa",
        "posicao": "Atacante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/diego-costa.png",
        "descricao": "Bicampeão da La Liga, destaque nas conquistas da Premier League e da Liga Europa e titular no ataque da seleção espanhola nas Copas do Mundo de 2014 e 2018, Diego Costa é um centroavente experiente com vasto currículo no futebol europeu. Com uma força física impressionante e ótima finalização, o atacante híspano-brasileiro chega para elevar o nível do elenco alivnegro.",
        "nome_completo": "Diego da Silva Costa",
        "nascimento": "07/10/1988, em Lagarto (SE)",
        "altura": "1,86m"
    },
    {
        "id": 53,
        "elenco": "masculino",
        "nome": "Matheus Nascimento",
        "posicao": "Atacante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/matheus-nascimento.png",
        "descricao": "Cria do Botafogo, centroavante goleador desde muito cedo, Matheus Nascimento tem passagem pela Seleção Brasileira sub-15 e diversos gols no início da carreira. Em 2020, com apenas 16 anos e muito futuro pela frente, assinou contrato e passou a treinar com os profissionais do Botafogo.",
        "nome_completo": "Matheus Nascimento de Paula",
        "nascimento": "03/03/2004, no Rio de Janeiro (RJ)",
        "altura": "1,82m"
    },
    {
        "id": 54,
        "elenco": "masculino",
        "nome": "Tiquinho Soares",
        "posicao": "Atacante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/tiquinho.png",
        "descricao": "Natural de Sousa, na Paraíba, Tiquinho Soares desenvolveu sua carreira no futebol português e conquistou muitos títulos na Europa. Goleador por onde passou, Soares volta ao seu país para assumir a missão ser o homem forte do ataque do Glorioso.",
        "nome_completo": "Francisco das Chagas Soares dos Santos",
        "nascimento": "17/01/1991, em Sousa (PB)",
        "altura": "1,87cm"
    },
    {
        "id": 55,
        "elenco": "masculino",
        "nome": "Carlos Alberto",
        "posicao": "Atacante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/carlosalberto.png",
        "descricao": "Carlos Alberto reforça a equipe do Glorioso e traz como principais características precisão e habilidade. O jovem atacante de 20 anos, revelado pelo América Mineiro, conta com convocações para a Seleção Brasileira de base e é um atleta com um futuro promissor.",
        "nome_completo": "Carlos Alberto Gomes da Silva Filho",
        "nascimento": "14/04/2002, em João Pessoa (PB)",
        "altura": "1,79cm"
    },
    {
        "id": 56,
        "elenco": "masculino",
        "nome": "Janderson",
        "posicao": "Atacante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/janderson.png",
        "descricao": "Artilheiro do Bahia de Feira na Série D de 2022, Janderson foi mais um jovem observado pelo departamento de scouting alvinegro para atuar pelo time Sub-23. Centroavante de bastante vigor físico e com bom aproveitamento nas finalizações, o jovem busca se firmar na equipe profissional em 2023.",
        "nome_completo": "Janderson de Carvalho Costa",
        "nascimento": "06/05/1999, em São João de Meriti (RJ)",
        "altura": "1m89"
    },
    {
        "id": 57,
        "elenco": "masculino",
        "nome": "Junior Santos",
        "posicao": "Atacante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/juniorsantos.png",
        "descricao": "Chegando do futebol asiático, Junior Santos é um atacante de bastante força e movimentação. O centroavante baiano, que é dono de um carisma peculiar fora do campo, chega para somar valor ao setor ofensivo do Alvinegro dentro das quatro linhas.",
        "nome_completo": "José Antonio dos Santos Júnior",
        "nascimento": "11/10/1994, em Conceição de Jacuípe (BA)",
        "altura": "1,88cm"
    },
    {
        "id": 58,
        "elenco": "masculino",
        "nome": "Matías Segovia",
        "posicao": "Atacante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/matias-segovia.png",
        "descricao": "Matías é um meia canhoto de bom drible e bastante velocidade, o atleta chega ao Glorioso para somar forças no setor ofensivo. Segovia Iniciou sua trajetória no Guaraní (PAR) e coleciona passagens nas categorias de base da Seleção Paraguaia, onde atuou como titular e foi um dos destaques no último Sul-Americano Sub-20.",
        "nome_completo": "Matías Emanuel Segovia Torales",
        "nascimento": "04/01/2003, em Caaguazú (PAR)",
        "altura": "Altura: 1,65m"
    },
    {
        "id": 59,
        "elenco": "masculino",
        "nome": "Diego Hernández",
        "posicao": "Atacante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/diego-hernandez.png",
        "descricao": "Destaque do Montevideo Wanderers, Hernández é um jovem de muito pontecial. Colecionando convocações para a Seleção celeste, o uruguaio se destaca em campo pela sua objetividade e boa finalização. Versátil, atua em mais de uma posição no campo ofensivo e chega elevar o nível do elenco.",
        "nome_completo": "Diego Manuel Hernández González",
        "nascimento": "22/06/2000, em Montevideo (URU)",
        "altura": "1,75m"
    },
    {
        "id": 60,
        "elenco": "masculino",
        "nome": "VALENTÍN ADAMO",
        "posicao": "Atacante",
        "imagem": "https://botafogo.com.br/images/elenco2023/roleta/valentinadamo.png",
        "descricao": "Com um bom jogo aéreo, velocidade e finalização certeira, Valentín Adamo é um jovem centroavente de muito potencial. Monitorado pelo Departamento de Scout do Glorioso, Adamo chega para somar forças no setor ofensivo após se destacar no futebol uruguaio.",
        "nome_completo": "Valentín Nicolás Adamo Reyes",
        "nascimento": "04/05/2002, em San Jacinto (URU)",
        "altura": "1,93m"
    }
]